// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: thrap.proto

/*
	Package thrapb is a generated protocol buffer package.

	It is generated from these files:
		thrap.proto

	It has these top-level messages:
		Build
		Secrets
		Envionment
		Component
		PackManifest
		Language
		Stack
		ChainHeader
		Identity
*/
package thrapb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Build struct {
	Dockerfile string `protobuf:"bytes,1,opt,name=Dockerfile,proto3" json:"Dockerfile,omitempty" hcl:"dockerfile"`
	Context    string `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty" hcl:"context" hcle:"omitempty"`
}

func (m *Build) Reset()                    { *m = Build{} }
func (m *Build) String() string            { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()               {}
func (*Build) Descriptor() ([]byte, []int) { return fileDescriptorThrap, []int{0} }

func (m *Build) GetDockerfile() string {
	if m != nil {
		return m.Dockerfile
	}
	return ""
}

func (m *Build) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

type Secrets struct {
	// Destination path
	Destination string `protobuf:"bytes,1,opt,name=Destination,proto3" json:"Destination,omitempty" hcl:"destination"`
	// Format ie. hcl, json, yaml etc.
	Format string `protobuf:"bytes,2,opt,name=Format,proto3" json:"Format,omitempty" hcl:"format"`
}

func (m *Secrets) Reset()                    { *m = Secrets{} }
func (m *Secrets) String() string            { return proto.CompactTextString(m) }
func (*Secrets) ProtoMessage()               {}
func (*Secrets) Descriptor() ([]byte, []int) { return fileDescriptorThrap, []int{1} }

func (m *Secrets) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Secrets) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

type Envionment struct {
	// File to read environment variables from
	File string `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty" hcl:"file"`
	// Key-Value pair of variables
	Vars map[string]string `protobuf:"bytes,2,rep,name=Vars" json:"Vars,omitempty" hcl:"vars" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Envionment) Reset()                    { *m = Envionment{} }
func (m *Envionment) String() string            { return proto.CompactTextString(m) }
func (*Envionment) ProtoMessage()               {}
func (*Envionment) Descriptor() ([]byte, []int) { return fileDescriptorThrap, []int{2} }

func (m *Envionment) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *Envionment) GetVars() map[string]string {
	if m != nil {
		return m.Vars
	}
	return nil
}

type Component struct {
	ID       string     `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty" hcle:"omit" yaml:"-"`
	Name     string     `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty" hcl:"name"`
	Version  string     `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty" hcl:"version" yaml:",omitempty" hcle:"omitempty"`
	Type     CompType   `protobuf:"bytes,4,opt,name=Type,proto3,casttype=CompType" json:"Type,omitempty" hcl:"type"`
	Language LanguageID `protobuf:"bytes,5,opt,name=Language,proto3,casttype=LanguageID" json:"Language,omitempty" hcl:"language" hcle:"omitempty" yaml:",omitempty"`
	// Build info if this is a buildable component
	Build *Build `protobuf:"bytes,6,opt,name=Build" json:"Build,omitempty" hcl:"build" yaml:",omitempty"`
	// Secrets for this component
	Secrets *Secrets `protobuf:"bytes,7,opt,name=Secrets" json:"Secrets,omitempty" hcl:"secrets" yaml:",omitempty"`
	// Port map so ports can be referenced by variables
	Ports map[string]int32 `protobuf:"bytes,8,rep,name=Ports" json:"Ports,omitempty" hcl:"ports" hcle:"omitempty" yaml:",omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// If dep then true is an external dep. If stack item then true exposes
	// to the internet
	External bool `protobuf:"varint,9,opt,name=External,proto3" json:"External,omitempty" hcl:"external" hcle:"omitempty" yaml:",omitempty"`
	// True if this is the head of the stack i.e. consumable api.
	Head bool `protobuf:"varint,10,opt,name=Head,proto3" json:"Head,omitempty" hcl:"head" hcle:"omitempty" yaml:",omitempty"`
	// Envionment variables
	Env *Envionment `protobuf:"bytes,11,opt,name=Env" json:"Env,omitempty" hcl:"env" hcle:"omitempty" yaml:",omitempty"`
	// Arbitrary KV config map
	Config map[string]string `protobuf:"bytes,12,rep,name=Config" json:"Config,omitempty" hcl:"config" hcle:"omitempty" yaml:",omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Component) Reset()                    { *m = Component{} }
func (m *Component) String() string            { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()               {}
func (*Component) Descriptor() ([]byte, []int) { return fileDescriptorThrap, []int{3} }

func (m *Component) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Component) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Component) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Component) GetType() CompType {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Component) GetLanguage() LanguageID {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Component) GetBuild() *Build {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *Component) GetSecrets() *Secrets {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *Component) GetPorts() map[string]int32 {
	if m != nil {
		return m.Ports
	}
	return nil
}

func (m *Component) GetExternal() bool {
	if m != nil {
		return m.External
	}
	return false
}

func (m *Component) GetHead() bool {
	if m != nil {
		return m.Head
	}
	return false
}

func (m *Component) GetEnv() *Envionment {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *Component) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

type PackManifest struct {
	// Pack name
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// User supplied constrained versions
	Versions []string `protobuf:"bytes,2,rep,name=Versions" json:"Versions,omitempty"`
	// Default version
	DefaultVersion string `protobuf:"bytes,3,opt,name=DefaultVersion,proto3" json:"DefaultVersion,omitempty"`
	// Base image
	Image string `protobuf:"bytes,4,opt,name=Image,proto3" json:"Image,omitempty"`
	// Files
	Files []string `protobuf:"bytes,5,rep,name=Files" json:"Files,omitempty"`
}

func (m *PackManifest) Reset()                    { *m = PackManifest{} }
func (m *PackManifest) String() string            { return proto.CompactTextString(m) }
func (*PackManifest) ProtoMessage()               {}
func (*PackManifest) Descriptor() ([]byte, []int) { return fileDescriptorThrap, []int{4} }

func (m *PackManifest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PackManifest) GetVersions() []string {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *PackManifest) GetDefaultVersion() string {
	if m != nil {
		return m.DefaultVersion
	}
	return ""
}

func (m *PackManifest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *PackManifest) GetFiles() []string {
	if m != nil {
		return m.Files
	}
	return nil
}

type Language struct {
	// Language name
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// User supplied constrained versions
	Versions       []string `protobuf:"bytes,2,rep,name=Versions" json:"Versions,omitempty"`
	DefaultVersion string   `protobuf:"bytes,3,opt,name=DefaultVersion,proto3" json:"DefaultVersion,omitempty"`
	// Source code file extensions of programming language. First if the primary
	// followed by any additionals such as header files etc.
	FileExts []string `protobuf:"bytes,4,rep,name=FileExts" json:"FileExts,omitempty"`
	// Extension of binaries generated by this language to ignore
	IgnoreFiles []string `protobuf:"bytes,5,rep,name=IgnoreFiles" json:"IgnoreFiles,omitempty"`
	// Base images usable for developed
	DevImages []string `protobuf:"bytes,6,rep,name=DevImages" json:"DevImages,omitempty"`
	// Base images usable to publish
	PubImages     []string `protobuf:"bytes,7,rep,name=PubImages" json:"PubImages,omitempty"`
	ScaffoldFiles []string `protobuf:"bytes,8,rep,name=ScaffoldFiles" json:"ScaffoldFiles,omitempty"`
}

func (m *Language) Reset()                    { *m = Language{} }
func (m *Language) String() string            { return proto.CompactTextString(m) }
func (*Language) ProtoMessage()               {}
func (*Language) Descriptor() ([]byte, []int) { return fileDescriptorThrap, []int{5} }

func (m *Language) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Language) GetVersions() []string {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *Language) GetDefaultVersion() string {
	if m != nil {
		return m.DefaultVersion
	}
	return ""
}

func (m *Language) GetFileExts() []string {
	if m != nil {
		return m.FileExts
	}
	return nil
}

func (m *Language) GetIgnoreFiles() []string {
	if m != nil {
		return m.IgnoreFiles
	}
	return nil
}

func (m *Language) GetDevImages() []string {
	if m != nil {
		return m.DevImages
	}
	return nil
}

func (m *Language) GetPubImages() []string {
	if m != nil {
		return m.PubImages
	}
	return nil
}

func (m *Language) GetScaffoldFiles() []string {
	if m != nil {
		return m.ScaffoldFiles
	}
	return nil
}

type Stack struct {
	ID           string                `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty" hcle:"omit" yaml:"-"`
	Name         string                `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty" hcl:"name"`
	Version      string                `protobuf:"bytes,4,opt,name=Version,proto3" json:"Version,omitempty" hcl:"version" hcle:"omitempty" yaml:",omitempty"`
	Components   map[string]*Component `protobuf:"bytes,5,rep,name=Components" json:"Components,omitempty" hcl:"components" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	Dependencies map[string]*Component `protobuf:"bytes,6,rep,name=Dependencies" json:"Dependencies,omitempty" hcl:"dependencies" yaml:",omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
	Description  string                `protobuf:"bytes,7,opt,name=Description,proto3" json:"Description,omitempty" hcl:"description" yaml:",omitempty" hcle:"omit"`
}

func (m *Stack) Reset()                    { *m = Stack{} }
func (m *Stack) String() string            { return proto.CompactTextString(m) }
func (*Stack) ProtoMessage()               {}
func (*Stack) Descriptor() ([]byte, []int) { return fileDescriptorThrap, []int{6} }

func (m *Stack) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Stack) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stack) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Stack) GetComponents() map[string]*Component {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *Stack) GetDependencies() map[string]*Component {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *Stack) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ChainHeader struct {
	Previous   []byte `protobuf:"bytes,1,opt,name=Previous,proto3" json:"Previous,omitempty"`
	Height     uint64 `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	Timestamp  int64  `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	DataDigest []byte `protobuf:"bytes,4,opt,name=DataDigest,proto3" json:"DataDigest,omitempty"`
}

func (m *ChainHeader) Reset()                    { *m = ChainHeader{} }
func (m *ChainHeader) String() string            { return proto.CompactTextString(m) }
func (*ChainHeader) ProtoMessage()               {}
func (*ChainHeader) Descriptor() ([]byte, []int) { return fileDescriptorThrap, []int{7} }

func (m *ChainHeader) GetPrevious() []byte {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *ChainHeader) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ChainHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ChainHeader) GetDataDigest() []byte {
	if m != nil {
		return m.DataDigest
	}
	return nil
}

type Identity struct {
	ID        string            `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty" hcl:"id"`
	Email     string            `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty" hcl:"email"`
	PublicKey []byte            `protobuf:"bytes,3,opt,name=PublicKey,proto3" json:"PublicKey,omitempty" hcl:"publickey"`
	Meta      map[string]string `protobuf:"bytes,4,rep,name=Meta" json:"Meta,omitempty" hcl:"meta" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Nonce     uint64            `protobuf:"varint,5,opt,name=Nonce,proto3" json:"Nonce,omitempty" hcl:"nonce"`
	Signature []byte            `protobuf:"bytes,6,opt,name=Signature,proto3" json:"Signature,omitempty" hcl:"signature"hcle:"omit"`
}

func (m *Identity) Reset()                    { *m = Identity{} }
func (m *Identity) String() string            { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()               {}
func (*Identity) Descriptor() ([]byte, []int) { return fileDescriptorThrap, []int{8} }

func (m *Identity) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Identity) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Identity) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Identity) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Identity) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Identity) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*Build)(nil), "Build")
	proto.RegisterType((*Secrets)(nil), "Secrets")
	proto.RegisterType((*Envionment)(nil), "Envionment")
	proto.RegisterType((*Component)(nil), "Component")
	proto.RegisterType((*PackManifest)(nil), "PackManifest")
	proto.RegisterType((*Language)(nil), "Language")
	proto.RegisterType((*Stack)(nil), "Stack")
	proto.RegisterType((*ChainHeader)(nil), "ChainHeader")
	proto.RegisterType((*Identity)(nil), "Identity")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Thrap service

type ThrapClient interface {
	RegisterStack(ctx context.Context, in *Stack, opts ...grpc.CallOption) (*Stack, error)
	RegisterIdentity(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*Identity, error)
	ConfirmIdentity(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*Identity, error)
}

type thrapClient struct {
	cc *grpc.ClientConn
}

func NewThrapClient(cc *grpc.ClientConn) ThrapClient {
	return &thrapClient{cc}
}

func (c *thrapClient) RegisterStack(ctx context.Context, in *Stack, opts ...grpc.CallOption) (*Stack, error) {
	out := new(Stack)
	err := grpc.Invoke(ctx, "/Thrap/RegisterStack", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thrapClient) RegisterIdentity(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*Identity, error) {
	out := new(Identity)
	err := grpc.Invoke(ctx, "/Thrap/RegisterIdentity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *thrapClient) ConfirmIdentity(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*Identity, error) {
	out := new(Identity)
	err := grpc.Invoke(ctx, "/Thrap/ConfirmIdentity", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Thrap service

type ThrapServer interface {
	RegisterStack(context.Context, *Stack) (*Stack, error)
	RegisterIdentity(context.Context, *Identity) (*Identity, error)
	ConfirmIdentity(context.Context, *Identity) (*Identity, error)
}

func RegisterThrapServer(s *grpc.Server, srv ThrapServer) {
	s.RegisterService(&_Thrap_serviceDesc, srv)
}

func _Thrap_RegisterStack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Stack)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThrapServer).RegisterStack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Thrap/RegisterStack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThrapServer).RegisterStack(ctx, req.(*Stack))
	}
	return interceptor(ctx, in, info, handler)
}

func _Thrap_RegisterIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThrapServer).RegisterIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Thrap/RegisterIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThrapServer).RegisterIdentity(ctx, req.(*Identity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Thrap_ConfirmIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThrapServer).ConfirmIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Thrap/ConfirmIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThrapServer).ConfirmIdentity(ctx, req.(*Identity))
	}
	return interceptor(ctx, in, info, handler)
}

var _Thrap_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Thrap",
	HandlerType: (*ThrapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterStack",
			Handler:    _Thrap_RegisterStack_Handler,
		},
		{
			MethodName: "RegisterIdentity",
			Handler:    _Thrap_RegisterIdentity_Handler,
		},
		{
			MethodName: "ConfirmIdentity",
			Handler:    _Thrap_ConfirmIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thrap.proto",
}

func (m *Build) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Build) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Dockerfile) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Dockerfile)))
		i += copy(dAtA[i:], m.Dockerfile)
	}
	if len(m.Context) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Context)))
		i += copy(dAtA[i:], m.Context)
	}
	return i, nil
}

func (m *Secrets) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Secrets) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Destination) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Destination)))
		i += copy(dAtA[i:], m.Destination)
	}
	if len(m.Format) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Format)))
		i += copy(dAtA[i:], m.Format)
	}
	return i, nil
}

func (m *Envionment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Envionment) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.File) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.File)))
		i += copy(dAtA[i:], m.File)
	}
	if len(m.Vars) > 0 {
		for k, _ := range m.Vars {
			dAtA[i] = 0x12
			i++
			v := m.Vars[k]
			mapSize := 1 + len(k) + sovThrap(uint64(len(k))) + 1 + len(v) + sovThrap(uint64(len(v)))
			i = encodeVarintThrap(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintThrap(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintThrap(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	return i, nil
}

func (m *Component) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Component) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Version) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Version)))
		i += copy(dAtA[i:], m.Version)
	}
	if len(m.Type) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Type)))
		i += copy(dAtA[i:], m.Type)
	}
	if len(m.Language) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Language)))
		i += copy(dAtA[i:], m.Language)
	}
	if m.Build != nil {
		dAtA[i] = 0x32
		i++
		i = encodeVarintThrap(dAtA, i, uint64(m.Build.Size()))
		n1, err := m.Build.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.Secrets != nil {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintThrap(dAtA, i, uint64(m.Secrets.Size()))
		n2, err := m.Secrets.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if len(m.Ports) > 0 {
		for k, _ := range m.Ports {
			dAtA[i] = 0x42
			i++
			v := m.Ports[k]
			mapSize := 1 + len(k) + sovThrap(uint64(len(k))) + 1 + sovThrap(uint64(v))
			i = encodeVarintThrap(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintThrap(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x10
			i++
			i = encodeVarintThrap(dAtA, i, uint64(v))
		}
	}
	if m.External {
		dAtA[i] = 0x48
		i++
		if m.External {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Head {
		dAtA[i] = 0x50
		i++
		if m.Head {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Env != nil {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintThrap(dAtA, i, uint64(m.Env.Size()))
		n3, err := m.Env.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if len(m.Config) > 0 {
		for k, _ := range m.Config {
			dAtA[i] = 0x62
			i++
			v := m.Config[k]
			mapSize := 1 + len(k) + sovThrap(uint64(len(k))) + 1 + len(v) + sovThrap(uint64(len(v)))
			i = encodeVarintThrap(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintThrap(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintThrap(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	return i, nil
}

func (m *PackManifest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackManifest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Versions) > 0 {
		for _, s := range m.Versions {
			dAtA[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.DefaultVersion) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.DefaultVersion)))
		i += copy(dAtA[i:], m.DefaultVersion)
	}
	if len(m.Image) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Image)))
		i += copy(dAtA[i:], m.Image)
	}
	if len(m.Files) > 0 {
		for _, s := range m.Files {
			dAtA[i] = 0x2a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *Language) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Language) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Versions) > 0 {
		for _, s := range m.Versions {
			dAtA[i] = 0x12
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.DefaultVersion) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.DefaultVersion)))
		i += copy(dAtA[i:], m.DefaultVersion)
	}
	if len(m.FileExts) > 0 {
		for _, s := range m.FileExts {
			dAtA[i] = 0x22
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.IgnoreFiles) > 0 {
		for _, s := range m.IgnoreFiles {
			dAtA[i] = 0x2a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.DevImages) > 0 {
		for _, s := range m.DevImages {
			dAtA[i] = 0x32
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.PubImages) > 0 {
		for _, s := range m.PubImages {
			dAtA[i] = 0x3a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if len(m.ScaffoldFiles) > 0 {
		for _, s := range m.ScaffoldFiles {
			dAtA[i] = 0x42
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *Stack) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Stack) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Version) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Version)))
		i += copy(dAtA[i:], m.Version)
	}
	if len(m.Components) > 0 {
		for k, _ := range m.Components {
			dAtA[i] = 0x2a
			i++
			v := m.Components[k]
			msgSize := 0
			if v != nil {
				msgSize = v.Size()
				msgSize += 1 + sovThrap(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovThrap(uint64(len(k))) + msgSize
			i = encodeVarintThrap(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintThrap(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if v != nil {
				dAtA[i] = 0x12
				i++
				i = encodeVarintThrap(dAtA, i, uint64(v.Size()))
				n4, err := v.MarshalTo(dAtA[i:])
				if err != nil {
					return 0, err
				}
				i += n4
			}
		}
	}
	if len(m.Dependencies) > 0 {
		for k, _ := range m.Dependencies {
			dAtA[i] = 0x32
			i++
			v := m.Dependencies[k]
			msgSize := 0
			if v != nil {
				msgSize = v.Size()
				msgSize += 1 + sovThrap(uint64(msgSize))
			}
			mapSize := 1 + len(k) + sovThrap(uint64(len(k))) + msgSize
			i = encodeVarintThrap(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintThrap(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if v != nil {
				dAtA[i] = 0x12
				i++
				i = encodeVarintThrap(dAtA, i, uint64(v.Size()))
				n5, err := v.MarshalTo(dAtA[i:])
				if err != nil {
					return 0, err
				}
				i += n5
			}
		}
	}
	if len(m.Description) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Description)))
		i += copy(dAtA[i:], m.Description)
	}
	return i, nil
}

func (m *ChainHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainHeader) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Previous) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Previous)))
		i += copy(dAtA[i:], m.Previous)
	}
	if m.Height != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintThrap(dAtA, i, uint64(m.Height))
	}
	if m.Timestamp != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintThrap(dAtA, i, uint64(m.Timestamp))
	}
	if len(m.DataDigest) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.DataDigest)))
		i += copy(dAtA[i:], m.DataDigest)
	}
	return i, nil
}

func (m *Identity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Identity) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.ID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.ID)))
		i += copy(dAtA[i:], m.ID)
	}
	if len(m.Email) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Email)))
		i += copy(dAtA[i:], m.Email)
	}
	if len(m.PublicKey) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.PublicKey)))
		i += copy(dAtA[i:], m.PublicKey)
	}
	if len(m.Meta) > 0 {
		for k, _ := range m.Meta {
			dAtA[i] = 0x22
			i++
			v := m.Meta[k]
			mapSize := 1 + len(k) + sovThrap(uint64(len(k))) + 1 + len(v) + sovThrap(uint64(len(v)))
			i = encodeVarintThrap(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintThrap(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintThrap(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if m.Nonce != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintThrap(dAtA, i, uint64(m.Nonce))
	}
	if len(m.Signature) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintThrap(dAtA, i, uint64(len(m.Signature)))
		i += copy(dAtA[i:], m.Signature)
	}
	return i, nil
}

func encodeVarintThrap(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Build) Size() (n int) {
	var l int
	_ = l
	l = len(m.Dockerfile)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	l = len(m.Context)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	return n
}

func (m *Secrets) Size() (n int) {
	var l int
	_ = l
	l = len(m.Destination)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	l = len(m.Format)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	return n
}

func (m *Envionment) Size() (n int) {
	var l int
	_ = l
	l = len(m.File)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	if len(m.Vars) > 0 {
		for k, v := range m.Vars {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovThrap(uint64(len(k))) + 1 + len(v) + sovThrap(uint64(len(v)))
			n += mapEntrySize + 1 + sovThrap(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *Component) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	l = len(m.Language)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	if m.Build != nil {
		l = m.Build.Size()
		n += 1 + l + sovThrap(uint64(l))
	}
	if m.Secrets != nil {
		l = m.Secrets.Size()
		n += 1 + l + sovThrap(uint64(l))
	}
	if len(m.Ports) > 0 {
		for k, v := range m.Ports {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovThrap(uint64(len(k))) + 1 + sovThrap(uint64(v))
			n += mapEntrySize + 1 + sovThrap(uint64(mapEntrySize))
		}
	}
	if m.External {
		n += 2
	}
	if m.Head {
		n += 2
	}
	if m.Env != nil {
		l = m.Env.Size()
		n += 1 + l + sovThrap(uint64(l))
	}
	if len(m.Config) > 0 {
		for k, v := range m.Config {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovThrap(uint64(len(k))) + 1 + len(v) + sovThrap(uint64(len(v)))
			n += mapEntrySize + 1 + sovThrap(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *PackManifest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	if len(m.Versions) > 0 {
		for _, s := range m.Versions {
			l = len(s)
			n += 1 + l + sovThrap(uint64(l))
		}
	}
	l = len(m.DefaultVersion)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	l = len(m.Image)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	if len(m.Files) > 0 {
		for _, s := range m.Files {
			l = len(s)
			n += 1 + l + sovThrap(uint64(l))
		}
	}
	return n
}

func (m *Language) Size() (n int) {
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	if len(m.Versions) > 0 {
		for _, s := range m.Versions {
			l = len(s)
			n += 1 + l + sovThrap(uint64(l))
		}
	}
	l = len(m.DefaultVersion)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	if len(m.FileExts) > 0 {
		for _, s := range m.FileExts {
			l = len(s)
			n += 1 + l + sovThrap(uint64(l))
		}
	}
	if len(m.IgnoreFiles) > 0 {
		for _, s := range m.IgnoreFiles {
			l = len(s)
			n += 1 + l + sovThrap(uint64(l))
		}
	}
	if len(m.DevImages) > 0 {
		for _, s := range m.DevImages {
			l = len(s)
			n += 1 + l + sovThrap(uint64(l))
		}
	}
	if len(m.PubImages) > 0 {
		for _, s := range m.PubImages {
			l = len(s)
			n += 1 + l + sovThrap(uint64(l))
		}
	}
	if len(m.ScaffoldFiles) > 0 {
		for _, s := range m.ScaffoldFiles {
			l = len(s)
			n += 1 + l + sovThrap(uint64(l))
		}
	}
	return n
}

func (m *Stack) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	if len(m.Components) > 0 {
		for k, v := range m.Components {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovThrap(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovThrap(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovThrap(uint64(mapEntrySize))
		}
	}
	if len(m.Dependencies) > 0 {
		for k, v := range m.Dependencies {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovThrap(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovThrap(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovThrap(uint64(mapEntrySize))
		}
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	return n
}

func (m *ChainHeader) Size() (n int) {
	var l int
	_ = l
	l = len(m.Previous)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovThrap(uint64(m.Height))
	}
	if m.Timestamp != 0 {
		n += 1 + sovThrap(uint64(m.Timestamp))
	}
	l = len(m.DataDigest)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	return n
}

func (m *Identity) Size() (n int) {
	var l int
	_ = l
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	if len(m.Meta) > 0 {
		for k, v := range m.Meta {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovThrap(uint64(len(k))) + 1 + len(v) + sovThrap(uint64(len(v)))
			n += mapEntrySize + 1 + sovThrap(uint64(mapEntrySize))
		}
	}
	if m.Nonce != 0 {
		n += 1 + sovThrap(uint64(m.Nonce))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovThrap(uint64(l))
	}
	return n
}

func sovThrap(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozThrap(x uint64) (n int) {
	return sovThrap(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Build) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowThrap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Build: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Build: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dockerfile", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dockerfile = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Context", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Context = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipThrap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthThrap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Secrets) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowThrap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Secrets: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Secrets: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Destination = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Format", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Format = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipThrap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthThrap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Envionment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowThrap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Envionment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Envionment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field File", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.File = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vars", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Vars == nil {
				m.Vars = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowThrap
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowThrap
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthThrap
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowThrap
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthThrap
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipThrap(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthThrap
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Vars[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipThrap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthThrap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Component) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowThrap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Component: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Component: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = CompType(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Language", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Language = LanguageID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Build", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Build == nil {
				m.Build = &Build{}
			}
			if err := m.Build.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Secrets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Secrets == nil {
				m.Secrets = &Secrets{}
			}
			if err := m.Secrets.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ports", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ports == nil {
				m.Ports = make(map[string]int32)
			}
			var mapkey string
			var mapvalue int32
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowThrap
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowThrap
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthThrap
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowThrap
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= (int32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipThrap(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthThrap
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Ports[mapkey] = mapvalue
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field External", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.External = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Head", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Head = bool(v != 0)
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Env", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Env == nil {
				m.Env = &Envionment{}
			}
			if err := m.Env.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Config == nil {
				m.Config = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowThrap
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowThrap
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthThrap
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowThrap
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthThrap
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipThrap(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthThrap
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Config[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipThrap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthThrap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PackManifest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowThrap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackManifest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackManifest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Versions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Versions = append(m.Versions, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Image = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Files", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Files = append(m.Files, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipThrap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthThrap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Language) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowThrap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Language: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Language: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Versions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Versions = append(m.Versions, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DefaultVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileExts", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileExts = append(m.FileExts, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IgnoreFiles", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IgnoreFiles = append(m.IgnoreFiles, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DevImages", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DevImages = append(m.DevImages, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubImages", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubImages = append(m.PubImages, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScaffoldFiles", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScaffoldFiles = append(m.ScaffoldFiles, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipThrap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthThrap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Stack) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowThrap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Stack: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Stack: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Components", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Components == nil {
				m.Components = make(map[string]*Component)
			}
			var mapkey string
			var mapvalue *Component
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowThrap
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowThrap
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthThrap
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowThrap
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= (int(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthThrap
					}
					postmsgIndex := iNdEx + mapmsglen
					if mapmsglen < 0 {
						return ErrInvalidLengthThrap
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &Component{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipThrap(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthThrap
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Components[mapkey] = mapvalue
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dependencies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Dependencies == nil {
				m.Dependencies = make(map[string]*Component)
			}
			var mapkey string
			var mapvalue *Component
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowThrap
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowThrap
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthThrap
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowThrap
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= (int(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthThrap
					}
					postmsgIndex := iNdEx + mapmsglen
					if mapmsglen < 0 {
						return ErrInvalidLengthThrap
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &Component{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipThrap(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthThrap
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Dependencies[mapkey] = mapvalue
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipThrap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthThrap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChainHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowThrap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Previous", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Previous = append(m.Previous[:0], dAtA[iNdEx:postIndex]...)
			if m.Previous == nil {
				m.Previous = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataDigest", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataDigest = append(m.DataDigest[:0], dAtA[iNdEx:postIndex]...)
			if m.DataDigest == nil {
				m.DataDigest = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipThrap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthThrap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Identity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowThrap
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Identity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Identity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Meta == nil {
				m.Meta = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowThrap
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowThrap
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthThrap
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowThrap
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthThrap
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipThrap(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthThrap
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Meta[mapkey] = mapvalue
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthThrap
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipThrap(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthThrap
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipThrap(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowThrap
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowThrap
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthThrap
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowThrap
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipThrap(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthThrap = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowThrap   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("thrap.proto", fileDescriptorThrap) }

var fileDescriptorThrap = []byte{
	// 1267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcb, 0x8e, 0xdb, 0x36,
	0x17, 0xfe, 0xed, 0xf1, 0xf5, 0xc8, 0x49, 0x26, 0xcc, 0x05, 0x82, 0x91, 0xdf, 0x72, 0xd9, 0xb4,
	0xf5, 0x22, 0xf1, 0x64, 0x9c, 0x14, 0x49, 0x06, 0x01, 0x0a, 0x78, 0xec, 0x34, 0x46, 0x2e, 0x9d,
	0x6a, 0xd2, 0x2c, 0xba, 0x09, 0x68, 0x99, 0xb6, 0x89, 0x91, 0x28, 0x43, 0xa2, 0x8d, 0x18, 0x59,
	0x14, 0xe8, 0x13, 0x14, 0x7d, 0x86, 0x3e, 0x4c, 0xd1, 0x55, 0xb7, 0xdd, 0x08, 0x45, 0xba, 0xeb,
	0x52, 0xcb, 0xac, 0x0a, 0x92, 0xb2, 0xa4, 0x24, 0xd3, 0xd4, 0x29, 0xd0, 0xcd, 0x8c, 0xce, 0xed,
	0xe3, 0xe1, 0xe1, 0xf9, 0x0e, 0x69, 0x30, 0xc4, 0x3c, 0x20, 0x8b, 0xee, 0x22, 0xf0, 0x85, 0xdf,
	0xbc, 0x3e, 0x63, 0x62, 0xbe, 0x1c, 0x77, 0x1d, 0xdf, 0xdb, 0x9b, 0xf9, 0x33, 0x7f, 0x4f, 0xa9,
	0xc7, 0xcb, 0xa9, 0x92, 0x94, 0xa0, 0xbe, 0xb4, 0x3b, 0x7e, 0x09, 0xe5, 0xfe, 0x92, 0xb9, 0x13,
	0x74, 0x0b, 0x60, 0xe0, 0x3b, 0x27, 0x34, 0x98, 0x32, 0x97, 0x9a, 0x85, 0x76, 0xa1, 0x53, 0xef,
	0x5f, 0x8c, 0x23, 0x6b, 0x77, 0xee, 0xb8, 0x07, 0x78, 0x92, 0x9a, 0xb0, 0x9d, 0xf3, 0x43, 0xf7,
	0xa0, 0x7a, 0xe8, 0x73, 0x41, 0x5f, 0x08, 0xb3, 0xa8, 0x42, 0x70, 0x1c, 0x59, 0x2d, 0x15, 0xe2,
	0x68, 0x3d, 0x6e, 0xcf, 0x1d, 0x97, 0x1e, 0x60, 0xdf, 0x63, 0x82, 0x7a, 0x0b, 0xb1, 0xc6, 0xf6,
	0x26, 0x04, 0xbb, 0x50, 0x3d, 0xa6, 0x4e, 0x40, 0x45, 0x88, 0x6e, 0x83, 0x31, 0xa0, 0xa1, 0x60,
	0x9c, 0x08, 0xe6, 0xf3, 0x64, 0xfd, 0x4b, 0x71, 0x64, 0x9d, 0xd7, 0xeb, 0x67, 0x36, 0x6c, 0xe7,
	0x3d, 0x51, 0x07, 0x2a, 0xf7, 0xfd, 0xc0, 0x23, 0x9b, 0x04, 0x76, 0xe3, 0xc8, 0x6a, 0xa8, 0x98,
	0xa9, 0x52, 0x63, 0x3b, 0xb1, 0xe3, 0x9f, 0x0a, 0x00, 0x43, 0xbe, 0x62, 0x3e, 0xf7, 0x28, 0x17,
	0x08, 0x43, 0xe9, 0x7e, 0xb6, 0xd5, 0xb3, 0x71, 0x64, 0x81, 0x0e, 0x53, 0x9b, 0x54, 0x36, 0x74,
	0x17, 0x4a, 0xcf, 0x48, 0x10, 0x9a, 0xc5, 0xf6, 0x4e, 0xc7, 0xe8, 0x5d, 0xea, 0x66, 0xe1, 0x5d,
	0xa9, 0x1f, 0x72, 0x11, 0xac, 0x73, 0xa1, 0x2b, 0x12, 0x84, 0xd8, 0x56, 0x21, 0xcd, 0xdb, 0x50,
	0x4f, 0x5d, 0xd0, 0x2e, 0xec, 0x9c, 0xd0, 0xb5, 0x5e, 0xca, 0x96, 0x9f, 0xe8, 0x22, 0x94, 0x57,
	0xc4, 0x5d, 0x52, 0x9d, 0xb5, 0xad, 0x85, 0x83, 0xe2, 0x9d, 0x02, 0xfe, 0xb3, 0x0a, 0xf5, 0x43,
	0xdf, 0x5b, 0xf8, 0x5c, 0x66, 0xd9, 0x81, 0xe2, 0x68, 0x90, 0xe4, 0x68, 0xc6, 0x91, 0x75, 0x31,
	0xab, 0x26, 0x6e, 0xaf, 0x89, 0xe7, 0x1e, 0xe0, 0xeb, 0xd8, 0x2e, 0x8e, 0x06, 0x72, 0x3f, 0x4f,
	0x88, 0x97, 0x00, 0xe6, 0x92, 0xe2, 0xc4, 0x93, 0xfb, 0x91, 0x36, 0xf4, 0x04, 0xaa, 0xcf, 0x68,
	0x10, 0xca, 0x0a, 0xef, 0x28, 0xb7, 0x5b, 0x71, 0x64, 0xdd, 0xd0, 0xb9, 0x6b, 0xfd, 0x06, 0xf4,
	0x5a, 0x76, 0x5e, 0xa7, 0x1c, 0x60, 0x02, 0x82, 0xba, 0x50, 0x7a, 0xba, 0x5e, 0x50, 0xb3, 0xa4,
	0xc0, 0x9a, 0xe9, 0x9a, 0x62, 0xbd, 0xa0, 0xf8, 0x75, 0x64, 0xd5, 0xe4, 0x46, 0xa4, 0x87, 0xad,
	0xfc, 0xd0, 0x73, 0xa8, 0x3d, 0x22, 0x7c, 0xb6, 0x24, 0x33, 0x6a, 0x96, 0x55, 0xcc, 0x61, 0x1c,
	0x59, 0xfb, 0x2a, 0xc6, 0x4d, 0x0c, 0xef, 0xae, 0xf7, 0x6e, 0x4a, 0xaf, 0x23, 0x0b, 0x36, 0x40,
	0xa3, 0x81, 0x9d, 0x82, 0xa2, 0x2f, 0x92, 0x76, 0x36, 0x2b, 0xed, 0x42, 0xc7, 0xe8, 0x55, 0xba,
	0x4a, 0xea, 0x7f, 0x14, 0x47, 0xd6, 0xff, 0xd5, 0x2a, 0x63, 0x29, 0x9f, 0x82, 0x68, 0x27, 0x34,
	0xf8, 0x32, 0x6d, 0x49, 0xb3, 0xaa, 0x20, 0x6a, 0xdd, 0x44, 0xee, 0x7f, 0x1c, 0x47, 0x96, 0xa5,
	0x40, 0x42, 0xad, 0x39, 0x0d, 0x26, 0x6d, 0xe8, 0xe7, 0x50, 0x3e, 0xf2, 0x03, 0x11, 0x9a, 0xb5,
	0xa4, 0x77, 0xd2, 0x33, 0xed, 0x2a, 0xbd, 0xee, 0x9d, 0x5e, 0x1c, 0x59, 0x5d, 0x85, 0xb9, 0x90,
	0xca, 0x6d, 0xf6, 0x6e, 0x6b, 0x5c, 0xf4, 0x35, 0xd4, 0x86, 0x2f, 0x04, 0x0d, 0x38, 0x71, 0xcd,
	0x7a, 0xbb, 0xd0, 0xa9, 0xf5, 0x3f, 0x4f, 0x6b, 0x49, 0x13, 0xc3, 0x56, 0x78, 0x29, 0x0c, 0x1a,
	0x42, 0xe9, 0x01, 0x25, 0x13, 0x13, 0x14, 0xdc, 0x7e, 0x1c, 0x59, 0xd7, 0x15, 0xdc, 0x9c, 0x92,
	0xc9, 0x56, 0x50, 0x2a, 0x1c, 0x7d, 0x05, 0x3b, 0x43, 0xbe, 0x32, 0x0d, 0x55, 0x3f, 0x23, 0x47,
	0x9a, 0xfe, 0x8d, 0x38, 0xb2, 0xae, 0xe9, 0x0c, 0xf9, 0x6a, 0x2b, 0x44, 0x89, 0x84, 0x1c, 0xa8,
	0x1c, 0xfa, 0x7c, 0xca, 0x66, 0x66, 0x43, 0x15, 0xf3, 0x72, 0xae, 0x98, 0xda, 0xa0, 0xab, 0x79,
	0x33, 0x8e, 0xac, 0xbd, 0xcd, 0xf0, 0x99, 0xb2, 0xd9, 0x56, 0x2b, 0x24, 0xd0, 0xcd, 0x3b, 0x00,
	0xd9, 0xc1, 0xfc, 0x13, 0x63, 0xcb, 0x39, 0xc6, 0x36, 0xef, 0x82, 0x91, 0xcb, 0xe2, 0x83, 0xc8,
	0xfe, 0x63, 0x01, 0x1a, 0x47, 0xc4, 0x39, 0x79, 0x4c, 0x38, 0x9b, 0xd2, 0x50, 0x20, 0x94, 0xb0,
	0x58, 0x47, 0x6b, 0xd6, 0x36, 0xa1, 0x96, 0x10, 0x4e, 0x4f, 0xa2, 0xba, 0x9d, 0xca, 0xe8, 0x53,
	0x38, 0x3b, 0xa0, 0x53, 0xb2, 0x74, 0xc5, 0x1b, 0xc4, 0xb6, 0xdf, 0xd2, 0xca, 0x14, 0x46, 0x9e,
	0xa4, 0x5d, 0x49, 0xa7, 0xa0, 0x04, 0xa9, 0x95, 0x73, 0x2e, 0x34, 0xcb, 0x0a, 0x56, 0x0b, 0xf8,
	0xfb, 0x62, 0x46, 0xd3, 0xff, 0x2c, 0xa1, 0x26, 0xd4, 0xe4, 0x6a, 0xc3, 0x17, 0x22, 0x34, 0x4b,
	0x1a, 0x63, 0x23, 0xa3, 0x36, 0x18, 0xa3, 0x19, 0xf7, 0x03, 0x9a, 0x4f, 0x2e, 0xaf, 0x42, 0x57,
	0xa0, 0x3e, 0xa0, 0x2b, 0xb5, 0x89, 0xd0, 0xac, 0x28, 0x7b, 0xa6, 0x90, 0xd6, 0xa3, 0xe5, 0x38,
	0xb1, 0x56, 0xb5, 0x35, 0x55, 0xa0, 0xab, 0x70, 0xe6, 0xd8, 0x21, 0xd3, 0xa9, 0xef, 0x4e, 0x34,
	0x7e, 0x4d, 0x79, 0xbc, 0xa9, 0xc4, 0xbf, 0x94, 0xa0, 0x7c, 0x2c, 0x88, 0x73, 0x92, 0x8c, 0xe0,
	0xe2, 0x07, 0x8c, 0xe0, 0x9d, 0xed, 0x46, 0x70, 0xe9, 0xef, 0x46, 0xf0, 0x16, 0x5d, 0x9b, 0x8e,
	0xe0, 0x47, 0x00, 0x29, 0x19, 0x74, 0xa9, 0x24, 0x3f, 0x54, 0xe6, 0x19, 0x4b, 0x92, 0x69, 0x93,
	0xdd, 0xe7, 0x4e, 0x6a, 0xc1, 0x76, 0x2e, 0x1e, 0x4d, 0xa1, 0x31, 0xa0, 0x0b, 0xca, 0x27, 0x94,
	0x3b, 0x2c, 0x29, 0xad, 0xd1, 0x33, 0x13, 0xbc, 0xbc, 0x49, 0x23, 0x76, 0xe2, 0xc8, 0xba, 0x9a,
	0xdc, 0xd0, 0x99, 0xed, 0xb4, 0x84, 0xdf, 0xc0, 0x45, 0xdf, 0xa8, 0xeb, 0xde, 0x09, 0xd8, 0x42,
	0x5d, 0xf7, 0x55, 0x55, 0x89, 0x8c, 0xbe, 0x93, 0xcc, 0xf6, 0xfe, 0x0b, 0x49, 0x3f, 0x06, 0x36,
	0xbe, 0xcd, 0x11, 0x9c, 0x7b, 0x6b, 0xcf, 0xa7, 0xb0, 0xb1, 0x9d, 0x67, 0xa3, 0xd1, 0x83, 0xac,
	0x4c, 0x79, 0x52, 0x3f, 0x84, 0xf3, 0xef, 0x6c, 0xf7, 0xdf, 0x82, 0xe1, 0xef, 0xc0, 0x38, 0x9c,
	0x13, 0xc6, 0xe5, 0x78, 0xa4, 0x81, 0xec, 0xfd, 0xa3, 0x80, 0xae, 0x98, 0xbf, 0x0c, 0x15, 0x56,
	0xc3, 0x4e, 0x65, 0x74, 0x19, 0x2a, 0x0f, 0x28, 0x9b, 0xcd, 0xf5, 0x7b, 0xa6, 0x64, 0x27, 0x92,
	0xec, 0xe9, 0xa7, 0xcc, 0xa3, 0xa1, 0x20, 0xde, 0x42, 0x35, 0xd8, 0x8e, 0x9d, 0x29, 0x50, 0x0b,
	0x60, 0x40, 0x04, 0x19, 0xb0, 0x19, 0x0d, 0x85, 0x6a, 0xac, 0x86, 0x9d, 0xd3, 0xe0, 0xdf, 0x8a,
	0x50, 0x1b, 0x4d, 0x28, 0x17, 0x4c, 0xac, 0xd1, 0x95, 0xdc, 0x9b, 0xa2, 0x11, 0x47, 0x56, 0x4d,
	0xd5, 0x9c, 0x4d, 0x74, 0x13, 0x7f, 0x02, 0xe5, 0xa1, 0x47, 0x98, 0x9b, 0x74, 0xfc, 0xb9, 0x38,
	0xb2, 0x0c, 0x3d, 0xb2, 0xa5, 0x16, 0xdb, 0xda, 0x8a, 0xf6, 0x15, 0xc7, 0x5c, 0xe6, 0x3c, 0xa4,
	0x6b, 0x95, 0x4f, 0xa3, 0x7f, 0x21, 0x8e, 0xac, 0x73, 0xfa, 0x32, 0x53, 0x96, 0x13, 0xba, 0xc6,
	0x76, 0xe6, 0x85, 0x6e, 0x43, 0xe9, 0x31, 0x15, 0x44, 0xd1, 0xdd, 0xe8, 0x5d, 0xe8, 0x6e, 0x12,
	0xea, 0x4a, 0xed, 0xdb, 0x6f, 0x29, 0x8f, 0x0a, 0x82, 0x6d, 0x15, 0x20, 0x53, 0x7a, 0xe2, 0x73,
	0x47, 0xbf, 0x19, 0x4a, 0xb9, 0x94, 0xb8, 0xd4, 0x62, 0x5b, 0x5b, 0xd1, 0x3d, 0xa8, 0x1f, 0xb3,
	0x19, 0x27, 0x62, 0x19, 0x50, 0xf5, 0x00, 0x68, 0xf4, 0x5b, 0x71, 0x64, 0x35, 0xf5, 0x9d, 0xbd,
	0xb1, 0xe0, 0x7c, 0xf7, 0x64, 0x01, 0xf2, 0xc1, 0x96, 0xe6, 0xf1, 0x21, 0x33, 0xbc, 0xf7, 0x12,
	0xca, 0x4f, 0xe5, 0x03, 0x1c, 0x59, 0x70, 0xc6, 0xa6, 0x33, 0x16, 0x0a, 0x1a, 0xe8, 0xc9, 0x51,
	0xd1, 0xbc, 0x69, 0x26, 0xff, 0x51, 0x07, 0x76, 0x37, 0x0e, 0xe9, 0x61, 0xd4, 0xd3, 0x32, 0x34,
	0xb3, 0x4f, 0xf4, 0x99, 0x6c, 0x64, 0x3e, 0x65, 0x81, 0xf7, 0x7e, 0xc7, 0xfe, 0xfe, 0xcf, 0xaf,
	0x5a, 0x85, 0x5f, 0x5f, 0xb5, 0x0a, 0xbf, 0xbf, 0x6a, 0x15, 0x7e, 0xf8, 0xa3, 0xf5, 0xbf, 0x6f,
	0xad, 0xdc, 0x0f, 0x00, 0xba, 0x9c, 0xfa, 0x01, 0x23, 0x7b, 0xea, 0x07, 0x82, 0xfe, 0x3b, 0x1e,
	0x57, 0xd4, 0xcb, 0xff, 0xe6, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x50, 0xb1, 0xd5, 0x79, 0x37,
	0x0c, 0x00, 0x00,
}
